version: '3'
services:
  db:
    build: dbServer
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: gogoGameDB
      MYSQL_USER: gogo
      MYSQL_PASSWORD: gogo
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
  game:
    build: gameServer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    scale: 3
    restart: always
    depends_on:
      - db
  lobby:
    build: lobbyServer
    scale: 2
    restart: always
    depends_on:
      - db
  ui:
    build: ui
    scale: 2
    restart: always
  nginx:
    image: nginx:latest
    volumes:
     - ./conf.d:/etc/nginx/conf.d
    ports:
    - "80:80"
    depends_on:
      - ui
      - lobby
